### ISSUE TITLE
@sane-shopify/server try to access `window`

### ISSUE THREAD

**Issue by liqueflies** [good-idea/sane-shopify#115]
Hello,
I setup a netlify configuration to deploy the lambda functions.
I used both netlify-lambda and netlify-cli and result was the same.

When I update a product I gave this error (I used unminified code in order to get the best possible log)

`{"errorType":"ReferenceError","errorMessage":"window is not defined","stack":["ReferenceError: window is not defined","    at index_es_syncUtils (/var/task/src/onProductUpdate.js:45029:5)","    at createSyncingClient (/var/task/src/onProductUpdate.js:45052:12)","    at createWebhooks (/var/task/src/onProductUpdate.js:45162:21)","    at createAWSWebhooks (/var/task/src/onProductUpdate.js:45198:20)","    at Object.<anonymous> (/var/task/src/onProductUpdate.js:23496:20)","    at __webpack_require__ (/var/task/src/onProductUpdate.js:20:30)","    at Object.<anonymous> (/var/task/src/onProductUpdate.js:45280:5)","    at __webpack_require__ (/var/task/src/onProductUpdate.js:20:30)","    at /var/task/src/onProductUpdate.js:84:18","    at Object.<anonymous> (/var/task/src/onProductUpdate.js:87:10)"]}`

Any idea?

**Comment by good-idea** [comment]
Hi @liqueflies , sorry about this! It's fixed in `0.17.0`. Thanks for reporting!
