### ISSUE TITLE
minVariantPrice and maxVariantPrice values loose decimal values

### ISSUE THREAD

**Issue by liqueflies** [good-idea/sane-shopify#117]
Hello,
not a blocking bug but just to signal that minVariantPrice and maxVariantPrice looses decimal values.

![Screenshot 2020-07-30 at 09 56 25](https://user-images.githubusercontent.com/12168237/88897016-efc06e00-d24a-11ea-97b0-b93bbf40f4a8.png)

True love for your work 🤟

**Comment by good-idea** [comment]
Just fixed this in `0.17.4`. Thanks for reporting the issue!
