### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by murmrs** [good-idea/sane-shopify#13]
While this project is in its, obvious, early stages, there is currently no license attached the project.

We're looking around for some solutions for an upcoming project, and while this one seems like something we'd like to contribute to, I'm hesitant to push my developers here without some project licensing information.

**Comment by good-idea** [comment]
Hi @murmrs , sorry for the slow delay, i'm not sure how I missed the notification. Thanks for opening the issue.

I've updated all of the package.json licenses to MIT and added a LICENSE doc. I'll be publishing some updates soon, so this will be published to NPM, if that's important.

I am getting close to a more stable beta - if you'd like to take a look at how I'm using it, you can take a look at the develop branch in:

https://github.com/good-idea/jemmawynne.com
https://github.com/good-idea/spinellikilcollin.com

(I'm developing `sane-shopify` and these two projects concurrently. Both of the website repos are pretty similar in how they use this package)

If you do give it a shot, feel free to add any issues with questions or suggestions.
