### ISSUE TITLE
Syncing relationships fails if no prior relationships exist

### ISSUE THREAD

**Issue by GLips** [good-idea/sane-shopify#130]
[This call in sync-utils/src/sanity/syncRelationships.ts](https://github.com/good-idea/sane-shopify/blob/74817038d7dd1cbb94e9ac4d55194a26ce8308f5/packages/sync-utils/src/sanity/syncRelationships.ts#L84) fails if there is no existing relationship.

```
TypeError: Cannot read property 'some' of undefined
```

I'm relatively new to Sanity, but it looks like it doesn't return null values if a specific field hasn't been initialized yet. When that's the case, `product.collections`—which `toDoc[bToAKey]` evaluates to—is null, and doesn't have access to `some()`.

[Previously](https://github.com/good-idea/sane-shopify/blame/9213c34480e68fd3886e677ed2c2f16291895544/packages/sync-utils/src/sanity/syncRelationships.ts#L137), it looks like we were setting values if they were missing. Probably need that for new instances again.

**Comment by good-idea** [comment]
Thanks for the fix, sorry it took me a bit to get to the PR!
