### ISSUE TITLE
add contributors

### ISSUE THREAD

**Issue by good-idea** [good-idea/sane-shopify#141]
Sorry @homerjam, i'm probably spamming you with notifications!

**Comment by good-idea** [comment]
@all-contributors please add @homerjam for code

**Comment by good-idea** [comment]
@all-contributors please add @nrgnrg for documentation & issues

**Comment by homerjam** [comment]
No problem, thanks for adding me to the contributors list! Still hoping to score my first Sanity/Shopify project - there's a couple of maybes in the pipeline! 🤞
