### ISSUE TITLE
Discussion: Multiple instances of Shopify

### ISSUE THREAD

**Issue by liqueflies** [good-idea/sane-shopify#147]
Hello again,

I have a discussion to bring to you.
Somethimes we have 2 or 3 instances of shopify in order to satisfy multiple listing price in different countries.
For now, we are using multiple instances of Sanity in order to achieve the desidered result.

But thinking about sanity desk we would be able to create documents with the country (us, eu for example) and refer products and collections into it) and able to filter both in the storefront and sanity cms keeping only 1 instance of sanity.

This can be achieved if

1. would be possible add multiple shopify sync stores
2. check for syncing issues between items

If I can be useful I wanted to dig into it but I wanted to discuss with you if

1. this can be in the scope of this plugin
2. Some guidelines to implement it

Thank you so much!

**Comment by good-idea** [comment]
We've had a few people request this, and it's definitely in scope. I won't have the time to implement this myself (for now), but if you'd like to give it a shot, feel free to put together a PR. Some preliminary things I see needing to happen:

- [ ] Storefront names & keys should be stored in an array in the sanity dataset
- [ ] Old storefront names & keys should be automatically migrated (if they exist) into the new array format
- [ ] Document sourceData should include the storefront name that they were synced from

However: I see one big issue with implementation: you'll need to create separate checkouts for products from different storefronts. Handling checkout it out of scope for this project, so it's not a blocker, but is definitely something to consider.

**Comment by liqueflies** [comment]
I think that it should contain different front-end based on Regions, each of them using the product from that shopify.
So you are connected to the storefront only with 1 storefront, but sharing the same cms :)

I'll try to start that and submit to you!
