### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by homerjam** [good-idea/sane-shopify#25]
Hi,

I'm working on a proposal for a client project which would combine Shopify and Sanity - if it goes ahead I think it would be great to make use of sane-shopify and contribute to it.

There's a feature I was wondering about to reduce friction for the client - do you think it's possible to create products in Sanity and push these to Shopify via the Shopify Admin API?

Have you considered this and are there any technical constraints preventing it that I might not have considered?

Thanks,
James

**Comment by good-idea** [comment]
Hi James,

Thanks for your question. It could be a feature down the road, but it complicates things a bit and is something that I won't be supporting for now. Most of my clients use Shopify for more than just editing products, so, the way I describe the setup to them is that Shopify is for managing your "Product Catalogue" and other biz affairs, while Sanity is for managing the website itself.

Framing it this way also reduces expectations that information added to Sanity might be used on other Shopify sales channels, for instance, an in-store POS.

I'm going to close this issue for now, but also flag it as a feature request for the future.
