### ISSUE TITLE
Compile issue after installing

### ISSUE THREAD

**Issue by chanmathew** [good-idea/sane-shopify#27]
Hi there,

First of all thanks for putting this project together!

I'm currently working on a custom storefront and after following the instructions in the readme, I'm running into this compile error which didn't exist prior to installing this package:

```
Error in ./node_modules/graphql-tag/src/index.js
Module not found: Error: Can't resolve 'graphql/language/parser' in '/Users/mathew/Dev/esqido-gatsby-sanity/studio/node_modules/graphql-tag/src'
 @ ./node_modules/graphql-tag/src/index.js 1:13-47
 @ ./node_modules/@sane-shopify/sync-utils/lib/index.es.js
 @ ./node_modules/@sane-shopify/sanity-plugin/lib/index.js
 @ ./node_modules/@sane-shopify/sanity-plugin/lib (all:part:@sanity/base/tool)
 @ ./node_modules/@sanity/default-layout/lib/defaultLayoutRouter.js
 @ ./node_modules/@sanity/default-layout/lib/components/DefaultLayoutContainer.js (part:@sanity/base/root)
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/normalize.css/normalize.css ./node_modules/@sanity/server/lib/browser/entry-dev.js
```

Here's my `schema.js`:
```
import createSchema from 'part:@sanity/base/schema-creator'
import schemaTypes from 'all:part:@sanity/base/schema-type'

import {
  createProductDocument,
  createCollectionDocument,
  saneShopifyObjects,
} from '@sane-shopify/sanity-plugin'

const product = createProductDocument()
const collection = createCollectionDocument()

export default createSchema({
  name: 'mySchema',
  types: schemaTypes.concat([...saneShopifyObjects, product, collection]),
})
```

My `sanity.json`:
```
"plugins": [
    "@sanity/base",
    "@sanity/components",
    "@sanity/default-layout",
    "@sanity/default-login",
    "@sanity/dashboard",
    "@sanity/desk-tool",
    "dashboard-widget-structure-menu",
    "dashboard-widget-document-list",
    "dashboard-widget-netlify",
    "@sane-shopify/sanity-plugin"
  ],
  "parts": [
    {
      "name": "part:@sanity/base/schema",
      "path": "./schemas/schema.js"
    },
    {
      "name": "part:@sanity/desk-tool/structure",
      "path": "./deskStructure.js"
    },
    {
      "implements": "part:@sanity/dashboard/config",
      "path": "./dashboardConfig.js"
    }
  ]
```

Any advice would be appreciated!

**Comment by good-idea** [comment]
Hi @chanmathew , thanks for opening the issue. If you `yarn add graphql` or `npm install graphql`, does that fix the issue?

This is the first time I'm working on an open source library, and still figuring out the best way to deal with dependencies... `graphql` is a package that has given me a particular amount of trouble with version compatibility issues. I might need to add it as a peer dependency.

It might also be a problem with how I am packaging the release. Also, have you installed the latest version, `0.6.1`?

**Comment by chanmathew** [comment]
Hey @good-idea, yeah it compiles now however I get this error when I open up localhost:3333:

![image](https://user-images.githubusercontent.com/2940761/72375654-78762300-36da-11ea-88b7-8d514d6a185e.png)

**Comment by good-idea** [comment]
I just pushed a new version - install `0.6.3` and give that a shot. I just did a setup from scratch and it's working on my end.

**Comment by chanmathew** [comment]
Awesome thanks Joseph! That worked. Will let you know if I run into any other issues!

**Comment by liqueflies** [comment]
If can be useful, just followed the docs and i got this error.
I think it's because is in peerDependecy that means that you have to install the package on your own.

https://github.com/good-idea/sane-shopify/pull/28/files

Talking about this PR.

Sounds familiar to you?
