### ISSUE TITLE
Feature Request: Customers

### ISSUE THREAD

**Issue by homerjam** [good-idea/sane-shopify#30]
I'm planning to use the Storefront API as the auth layer for a GraphQL API that wraps Sanity/Shopify API requests. I'll then store additional sensitive data for each customer in Sanity which customers will have access to if they are logged in.

In order to do this I'll need to sync customer data - initially only the ID will be strictly necessary but name/email etc would obviously be useful.

With this in mind is there a way we can make the syncing system more flexible ie. not tied to products/collections so that it can be used for variants, customers etc? For instance there appears to be some repeated code in the fetching utils.

**Comment by good-idea** [comment]
This is definitely possible. But, not everyone will want this, and for some storefronts, could turn into 1000s of sanity documents to keep in sync - we'd need to add an option to the plugin configuration to enable this.

**Comment by good-idea** [comment]
Actually, this might be getting into territory that I'm not sure about. So far, all of the internals use the Storefront API, which is very "secure" in the sense that all of the data is public.

The Storefront token is stored in the dataset. If a user's Sanity dataset is public (which I am assuming most will be), that's no problem - it's OK if this token is public. If we were to support syncing customers, users would need to enter a private API key, and set up custom permissions in Sanity to protect it.

This would mean that we would have to implement some kind of security check - to make sure that a user has set the configuration data and customer documents as private - before allowing them to add sensitive data. It would be a good amount of work, and then we would need to be worrying about security as the project moves forward.

I haven't made a hard decision about this yet, but I am considering limiting the functionality of the whole project to the Storefront API only. The general philosophy behind using Sane Shopify is that you'll use Sanity to manage the public aspects of your website, and Shopify to manage the product catalogue and all of the business.

That being said, parts of the `sync-utils` package could be generalized and made available, so you could use those to write your own solution for this.

@homerjam , what is the use case you're thinking about?

**Comment by homerjam** [comment]
> This is definitely possible. But, not everyone will want this, and for some storefronts, could turn into 1000s of sanity documents to keep in sync - we'd need to add an option to the plugin configuration to enable this.

This is a good point in general - for example I don't think my project will make use of collections.

I think you could be right about limiting the scope here. The API I'm planning to use is part of the Storefront API, however it's used to create or update single customers only and requires a customer access token (obtained with email/password) to do so. So in that sense it wouldn't really make a lot of sense to include in the sync utils. I should probably roll my own utility for this as part of the API wrapper I intend to create. That said perhaps we could make space for a customer document type and webhook. This could perhaps store ID's only or come with a clear warning that the dataset must be private.

https://help.shopify.com/en/api/storefront-api/reference/object/customer
https://help.shopify.com/en/api/storefront-api/reference/object/customeraccesstoken
https://help.shopify.com/en/api/storefront-api/reference/mutation/customercreate
https://help.shopify.com/en/api/storefront-api/reference/mutation/customeraccesstokencreate

Side note - have you seen these, I wonder if they could be useful?

https://github.com/Shopify/graphql-js-client
https://github.com/Shopify/graphql-js-schema

**Comment by good-idea** [comment]
Closing this for now, as syncing customers won't be supported out of the box. We can open another issue to track settings up some utilities to make it easy to do this down the line.
