### ISSUE TITLE
Feature: extend product variants

### ISSUE THREAD

**Issue by good-idea** [good-idea/sane-shopify#33]
In progress - working on adding product variants as an array of sub-fields to the Sanity documents, allowing you to extend on these variants. For instance, adding a separate descriptions or galleries of images.

**Comment by good-idea** [comment]
@homerjam: from #22 

> Also I know you have your own roadmap so maybe I'll attempt to tackle this myself but variants are higher up the priority list than deletions for me!

This is higher on my list as well. Is there anything in particular you're trying to achieve?

**Comment by homerjam** [comment]
It's early stages of the project so we're still planning things out but the store will have products with lots of variables, I wouldn't say there's anything particular - storing the `sourceData` as you're doing now should suffice I think. My only concern there is (as was pointed out in the round table video) that this could end up binding the project to a particular Storefront API version. Shopify has been rapidly changing so I wonder if there's anything sensible we could do to mitigate this - perhaps even creating our own product/variant/collection schemas rather than storing all the nodes/edges as is.

**Comment by good-idea** [comment]
Yeah, that API is kind of all over the place. I just realized that the code was using the `/api/graphql` endpoint - I've locked it into `2020-01` for now. Moving forward, updating this will require checking if there are any breaking changes to the Storefront API that would affect `sourceData` - if so, that would be a breaking change for people relying on `sourceData`, and we would version appropriately.

**Comment by chanmathew** [comment]
Just chiming in on how our store uses variants:

We currently have products that are 1-pack or 2-pack, and customers can choose either, with different pricing and images. So being able to pull these in and read the right images, maybe add additional fields to each variants for additional frontend rendering/logic would be pretty helpful.

**Comment by good-idea** [comment]
Done in https://github.com/good-idea/sane-shopify/pull/44

please give it a shot!

**Comment by chanmathew** [comment]
Just upgraded and now when I compile the Studio I get this error:

```
Unknown type: productVariant. Valid types are: shopifyImageEdge, shopifySourceImages, shopifySourceImage, saneProductOption, saneMoney, saneProductPriceRange, collectionsConnection, productVariantEdge, productVariantEdges, productVariantsConnection, shopifyProductSource, selectedOption, shopifyProductVariantSource, productsConnection, shopifyCollectionSource, linkedCollections, pageInfo, shopifyNode, edge, shopifyEdges, shopifyProduct, shopifyCollection, array, block, boolean, datetime, date, document, email, file, geopoint, image, number, object, reference, slug, string, telephone, text and url
```

![image](https://user-images.githubusercontent.com/2940761/73130094-e31f3c80-3fbf-11ea-9b6a-61989e41e3df.png)

**Comment by good-idea** [comment]
There's another object you need to import - - see the note about 0.7.0 at
the bottom the the Readme.

Until 1.0 is released, minor version changes might be breaking - - - but
I'll put notes in the Readme when there are things you need to do to
migrate
