### ISSUE TITLE
Issue syncing on 0.7.0

### ISSUE THREAD

**Issue by chanmathew** [good-idea/sane-shopify#45]
Hey @good-idea, thanks for adding in product variants!

So I got it compiling fine now, however when I try to resync my shopify products (my products on Shopify has actual variants so I'm trying to resync to see if they match up to the new variants schemas), collections will sync fully, however when it gets to syncing products it gets stuck at 0, and I see the following error in console:

![image](https://user-images.githubusercontent.com/2940761/73143364-2da7c400-4067-11ea-92db-fe77cad373d1.png)

Here's my latest `schema.js`:

```
import createSchema from 'part:@sanity/base/schema-creator'
import schemaTypes from 'all:part:@sanity/base/schema-type'

import {
  createProductDocument,
  createCollectionDocument,
  createProductVariant,
  saneShopifyObjects,
} from '@sane-shopify/sanity-plugin'

const product = createProductDocument({
  fields: [
    {
      title: 'Tags',
      name: 'tags',
      type: 'array',
      of: [{ type: 'string' }],
      options: {
        layout: 'tags',
      },
    },
  ],
})
const productVariant = createProductVariant()
const collection = createCollectionDocument()

export default createSchema({
  name: 'mySchema',
  types: schemaTypes.concat([
    ...saneShopifyObjects,
    product,
    productVariant,
    collection,
  ]),
})
```

**Comment by good-idea** [comment]
`0.7.2` should fix this. If not, it's now published with sourcemaps, so that error message will be more helpful!

**Comment by chanmathew** [comment]
That worked, thanks for the quick fix! :)
