### ISSUE TITLE
variant sourceData not showing up in GraphQL Schema

### ISSUE THREAD

**Issue by chanmathew** [good-idea/sane-shopify#48]
Hey guys,

So I'm trying to use the new Product Variant fields that was added and I noticed that there's no ShopifyId at the variant level, it doesn't appear to be in `sanityShopifyProduct` nor `allSanityShopifyProduct`.

The use case here is I need the variant ShopifyId in order to add the right variant to cart.

This is everything I see under `sanityShopifyProduct`:
![image](https://user-images.githubusercontent.com/2940761/73408830-76f84d80-42cb-11ea-90a9-7e2c1c357d1e.png)

**Comment by good-idea** [comment]
Do you see the `id` when you inspect the data straight from the Sanity Dashboard? 

![image](https://user-images.githubusercontent.com/11514928/73594586-99fa4b80-44dd-11ea-984b-ca5ad5e3f94d.png)

And, it looks like you're using GraphiQL to build your queries. Is this pointing straight to the Sanity GraphQL API or is this Gatsby?

I should rename it to `shopifyVariantId` regardless. I'll address this in the next patch.

**Comment by chanmathew** [comment]
Ah yes I do see it under Inspect in Sanity, perhaps the gatsby-source-sanity plugin isn't pulling all the fields as the schema in GraphiQL is coming from that. But it should be connected to the Sanity Schema?

![image](https://user-images.githubusercontent.com/2940761/73670824-ed080600-4677-11ea-8b19-a8a4613b35bd.png)

**Comment by good-idea** [comment]
I published 0.7.4 which renames the field to `shopifyVariantId`. Maybe that will do the trick for the gatsby plugin?

**Comment by chanmathew** [comment]
@good-idea So I upgraded, redeployed the Sanity playground, and restarted Gatsby dev and I see `shopifyVariantID` now but it just shows null:

![image](https://user-images.githubusercontent.com/2940761/73684048-65c78c00-4691-11ea-96ba-ef11490c8565.png)

Also in Sanity inspect it looks like the key still has the key of `id`:
![image](https://user-images.githubusercontent.com/2940761/73684775-d8853700-4692-11ea-839c-3a537eb3afcf.png)

**Comment by good-idea** [comment]
@chanmathew I just came up with the same issue in my own project - not through Gatsby, but through the Sanity GrahphQL api. For some reason it's not including the additional source data in the schema. I've updated the title of this issue to be more specific.

**Comment by chanmathew** [comment]
Oh I see, thanks for the update! For now I’ll just read from the Shopify source plugin to read variant data.

**Comment by good-idea** [comment]
@chanmathew `0.8.0` should fix this. Let me know if you come across any missing fields in the GraphQL / gatsby schema. (Note that this release has some breaking changes, see the bottom of the readme)

Closing the issue for now, if anything isn't working I can re-open.

**Comment by chanmathew** [comment]
Thanks @good-idea, updated and it is working as expected:

![image](https://user-images.githubusercontent.com/2940761/74191372-76dc4400-4c21-11ea-8806-46a771e7d52c.png)

Small note, the key of the variant is currently `shopifyVariantID` instead of camelCase `shopifyVariantId`, not sure if that is intentional or not but just want to point that out incase it breaks anything upon change,
