### ISSUE TITLE
localFile missing from `images`

### ISSUE THREAD

**Issue by rafaelderolez** [good-idea/sane-shopify#54]
Hey Joseph,

I was trying to transform Product Images using 
```
allSanityShopifyProduct() {
  edges {
    node {
      sourceData {
        images {
          edges {
            node {
              localFile {
                childImageSharp {
                  fluid(maxWidth: 910) {
                    ...GatsbyImageSharpFluid_withWebp
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

but looks like that's not supported. Is this something you're interested in having in the package, or are we better off adding an image field in Sanity?

I'm thinking ahead about clients having to add images twice: Once in Shopify from (needed to see the thumbnail on checkout) and then once in Sanity.

Interested to see what you think.

**Comment by good-idea** [comment]
Hi Rafael,


I'm not too familiar with the gatsby plugin, and I'm not sure if there is a way to get the `sourceData` images to transform to local files. I'd recommend adding an image field in Sanity - from what I recall, the gatsby/sanity plugin does a good job here, and you'll also get the crop/hotspot functionality.

I have added a few extra image sizes (`w300`, `w600`, and `w900`, I believe) to the `sourceData` images, which could be helpful to make using them responsive.

I'm still having my clients add images to products (and their variants) in Shopify - if they are using any other sales channels like the buy button or POS, they'll need them for that. It's still annoying that they need to manage this kind of content in two places, but the only way I see getting around this is making the `sourceData` editable and syncing it back *to* shopify, which would add a whole new layer and is out of scope for this project right now.
