### ISSUE TITLE
"Connected to shopify storefront", before having actually connected

### ISSUE THREAD

**Issue by benjaminsehl** [good-idea/sane-shopify#55]
Hey there — giving this plugin a go again! Initial setup does look much cleaner in 0.8! Unfortunately once I get to localhost:3333/shopify, I'm hit with the "Connected to shopify storefront" screen and can't Unlink. Haven't set it up yet so it's odd that that's happening. 

Any ideas on a workaround?

**Comment by good-idea** [comment]
Hi @benjaminsehl, I'm sorry I missed this issue, not sure how it slipped by. This is fixed in 0.9.0 - give it a shot and let me know if you have any more issues. Sorry about that!
