### ISSUE TITLE
Sync from Shopify hangs

### ISSUE THREAD

**Issue by tylermcrobert** [good-idea/sane-shopify#76]
First off, awesome project. I can't wait to see where this goes. 

### The Issue
After connecting my store and selecting "Sync from Shopify", the button indicates loading for awhile and when I look in the console I see the following:

`Uncaught (in promise) TypeError: Cannot read property 'products' of null`

**Comment by good-idea** [comment]
Thanks for filing this! Does the error include a sourcemap or say what file & line where the error occured?

**Comment by tylermcrobert** [comment]
I've backed out of it for now but I believe it was here: https://github.com/good-idea/sane-shopify/blob/78a33d6a810a1b9e74475cda9615a0034e9ea843/packages/sync-utils/src/shopify/fetchAllShopifyProducts.ts#L70

I can pretty easily spin it back up and retry if this isn't helpful

**Comment by good-idea** [comment]
Hey @tylermcrobert , I believe that this issue has been resolved - could you give it another try on your end? I'm going to close this for now, feel free to re-open if it still happens for you.
